export const GENERIC_SAVE_EXTENSIONS = [
    'sol',
    'db',
    'sqlite',
    'sqlite3',
    'db3',
    's3db',
    'sl3',
    'sqlitedb',
    'msgpack',
    'mpack',
    'cbor',
    'bson',
    'es3',
    'dat',
    'nrbf',
    'bytes',
    'pkl',
    'pickle',
    'cfg',
    'yaml',
    'yml',
    'toml',
    'properties',
    'props',
    'conf',
    'csv',
    'tsv',
    'zip',
    'gz',
    'zlib',
    'deflate',
    'bz2',
    'bzip2',
    'lz4',
    'zst',
    'zstd',
    'b64',
    'base64',
    'lzstring',
    'lzstr',
    'xml',
];

export const SMART_UPLOAD_EXTENSIONS = [
    'rpgsave',
    'rmmzsave',
    'rvdata2',
    'rvdata',
    'rxdata',
    'lsd',
    'sav',
    'save',
    'xml',
    'plist',
    'prefs',
    'ini',
    'json',
    'txt',
    'nson',
    ...GENERIC_SAVE_EXTENSIONS,
];

export const GENERIC_EXTENSION_SET = new Set(GENERIC_SAVE_EXTENSIONS);
export const GENERIC_DOTTED_EXTENSION_SET = new Set(GENERIC_SAVE_EXTENSIONS.map((ext) => `.${ext}`));
export const SMART_UPLOAD_ACCEPT = Array.from(new Set(SMART_UPLOAD_EXTENSIONS)).map((ext) => `.${ext}`).join(',');
